# 5 Numpy Array Manipulation function that we must Know

- np.flatten()  
- ndarray.T() 
- np.rot90()
- np.swapaxes()
- np.squeeze()


In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "ashishdotc4/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/ashishdotc4/numpy-array-operations


'https://jovian.ai/ashishdotc4/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [6]:
# # List of functions explained 
function1 = np.flatten()  
function2 = np.T
function3 = np.rot90()
function4 = np.swapaxes()
function5 = np.squeeze()

AttributeError: module 'numpy' has no attribute 'flatten'

## Function 1 - np.flatten()

* np.flatten() is used to get a copy of an given array collapsed into one dimension.

In [7]:
# Example 1 - working (change this)
arr1 = np.array([[1, 2], 
        [3, 4.]])
arr1

array([[1., 2.],
       [3., 4.]])

In [8]:
arr1.flatten("F")

array([1., 3., 2., 4.])

np.flatten() takes the 2d array and convert it into 1d array.

In [9]:
# Example 2 - working
arr2 = np.array([[5, 6, 7], 
        [8, 9, 10]])
arr2.flatten()


array([ 5,  6,  7,  8,  9, 10])

In [10]:
arr2.flatten("K")

array([ 5,  6,  7,  8,  9, 10])

np.flatten() takes the 2d array and convert it into 1d array.

In [11]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[[1, 2], 
               [3, 4.]],
                
             [[5, 6], 
             [8, 9]]]

arr1.flatten("F")

AttributeError: 'list' object has no attribute 'flatten'

It breaks because np.flatten() doenot work with list so first it must be converted into numpy array

np.flatten() is used When we want to get a copy of an  array  into one dimension.

In [12]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "ashishdotc4/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/ashishdotc4/numpy-array-operations


'https://jovian.ai/ashishdotc4/numpy-array-operations'

## Function 2 - np.T

ndarray.T() is used to make a Transpose of an array having dimension greater than or equal to 2.

In [13]:
# Example 1 - working
arr1=np.array([[1,2,3,4],
              [5,6,7,8]])
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
arr1.shape

(2, 4)

In [15]:
arr1.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [16]:
arr1.T.shape

(4, 2)

ndarray.T() takes the numpy array and convert its rows into columns and column into rows i.e, Convert  the shape of an array

In [17]:
# Example 2 - working
arr2=np.array([[[1,2,3,4],
              [5,6,7,8]],
               
               [[9,0,1,2],
               [3,4,5,6]]])
arr2

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[9, 0, 1, 2],
        [3, 4, 5, 6]]])

In [18]:
arr2.shape

(2, 2, 4)

In [19]:
arr2.T

array([[[1, 9],
        [5, 3]],

       [[2, 0],
        [6, 4]],

       [[3, 1],
        [7, 5]],

       [[4, 2],
        [8, 6]]])

In [20]:
(arr2.T).shape

(4, 2, 2)

ndarray.T() takes the numpy array and covert its rows into columns and column into rows i.e, Convert the shape of an array

In [21]:
# Example 3 - breaking (to illustrate when it breaks)
arr3=np.array([2,4,6,8])
arr3.T

array([2, 4, 6, 8])

It doenot Work With 1D array because in 1D array,NumPy's transpose() effectively reverses the shape of an array.this means it has no effect.

ndarray.T() is used When we want to make a Transpose of an array having dimension greater than or equal to 2.

In [ ]:
jovian.commit()

## Function 3 - np.rot90()

np.rot90() method is used When we want to rotate a 2d or more than 2d array by 90 degree.  

In [22]:
# Example 1 - working
arr1=np.array([[1,2,3,4],
              [5,6,7,8]])
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
arr1.shape

(2, 4)

In [24]:
np.rot90(arr1,1)

array([[4, 8],
       [3, 7],
       [2, 6],
       [1, 5]])

Here,np.rot90() takes the arr1 and rotate the given array by 90 1 times  and gives the new array which is rotated by 90 

In [25]:
# Example 2 - working
arr2=np.array([[[2,4,6,8],
               [10,12,14,16]],
              [[18,20,22,24],
              [26,28,30,32]]])
arr2

array([[[ 2,  4,  6,  8],
        [10, 12, 14, 16]],

       [[18, 20, 22, 24],
        [26, 28, 30, 32]]])

In [26]:
arr2.shape

(2, 2, 4)

In [27]:
np.rot90(arr2,2)

array([[[26, 28, 30, 32],
        [18, 20, 22, 24]],

       [[10, 12, 14, 16],
        [ 2,  4,  6,  8]]])

Here,np.rot90() takes the arr2 and rotate the given array by 90 by 2 times and gives the new array which is rotated by 90 twice

In [28]:
# Example 3 - breaking (to illustrate when it breaks)
arr3=np.array([1,2,3,4])
arr3

array([1, 2, 3, 4])

In [29]:
np.rot90(arr3,1)

ValueError: Axes must be different.

Here,np.rot90() break because in 1d array axes are same bt It can be rotated if it is defined as a two-dimensional array of only one row.

np.rot90() method is used When we want to rotate a 2d or more than 2d array by 90 degree.

In [ ]:
jovian.commit()

## Function 4 - np.swapaxes()

np.swapaxes() method is used when we want to Interchange two axes of an array.

In [30]:
# Example 1 - working
arr1=np.array([[1,2,3,4],
              [5,6,7,8]])
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
np.swapaxes(arr1,0,1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

np.swapaxes() method takes the 2d array and swap its axis into(0,1)

In [32]:
# Example 2 - working
arr2=np.array([[[1,2,3,4],
               [5,6,7,8]],
              [[9,0,1,2],
           [3,4,5,6]]])
arr2  

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[9, 0, 1, 2],
        [3, 4, 5, 6]]])

In [33]:
np.swapaxes(arr2,1,2)

array([[[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]],

       [[9, 3],
        [0, 4],
        [1, 5],
        [2, 6]]])

np.swapaxes() method takes the 3d array and swap its axis into(1,2)

In [34]:
# Example 3 - breaking (to illustrate when it breaks)
arr3=np.array([1,2,3,4])
arr3

array([1, 2, 3, 4])

In [35]:
np.swapaxes(arr3,2,1)

AxisError: axis1: axis 2 is out of bounds for array of dimension 1

In 1d array,np.swapaxes() method can't change axes because there is only one 1 axis present in it while in 2d or more than 2d array more axes are present in it so it works fine with it 

np.swapaxes() method is used when we want to Interchange two axes of an array.

In [ ]:
jovian.commit()

## Function 5 -  np.squeeze()

np.squeeze() method is used when we have to squeezed out axes of length one from an array.

In [36]:
# Example 1 - working
arr1=np.array([[1,2,3,4]])
arr1

array([[1, 2, 3, 4]])

In [37]:
arr1.shape

(1, 4)

In [38]:
np.squeeze(arr1,axis=0)

array([1, 2, 3, 4])

In [39]:
np.squeeze(arr1,axis=0).shape

(4,)

np.squeeze() takes an array of size (1,4) and squeezed the size of 0th axis and return the squeezed array of size (4,)  

In [40]:
# Example 2 - working
arr2=np.array([[[1,2,3,4]]])
arr2

array([[[1, 2, 3, 4]]])

In [41]:
arr2.shape

(1, 1, 4)

In [42]:
np.squeeze(arr2,axis=1)

array([[1, 2, 3, 4]])

In [43]:
np.squeeze(arr2,axis=1).shape

(1, 4)

np.squeeze() takes an array of size (1,1,4) and squeezed the size of 1st axis and return the squeezed array of size (1,4)

In [44]:
# Example 3 - breaking (to illustrate when it breaks)
arr3=np.array([[[1,2,3,4]]])
arr3

array([[[1, 2, 3, 4]]])

In [45]:
arr3.shape

(1, 1, 4)

In [46]:
np.squeeze(arr2,axis=2)

ValueError: cannot select an axis to squeeze out which has size not equal to one

np.squeeze() method can only squeeze out  the axes which has size equal to one 

np.squeeze() method is used when we have to squeezed out axes of length one from an array.

In [ ]:
jovian.commit()

## Conclusion

In this notebook I covered about 5 Numpy Array Manipulation function that we must Know for array manipulation
- np.flatten()
- ndarray.T()
- np.rot90()
- np.swapaxes()
- np.squeeze()

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* np.flatten() : https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html
* ndarray.T() : https://numpy.org/doc/stable/reference/generated/numpy.ndarray.T.html
* np.swapaxes() : https://numpy.org/doc/stable/reference/generated/numpy.swapaxes.html
* np.squeeze() : https://numpy.org/doc/stable/reference/generated/numpy.squeeze.html

In [ ]:
jovian.commit()

In [48]:
!git init


Reinitialized existing Git repository in /home/jovyan/.git/


In [50]:
!git add .

In [51]:
!git status

On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   .bash_logout
	new file:   .bashrc
	new file:   .cache/matplotlib/fontlist-v330.json
	new file:   .cache/pip/http/2/f/9/b/6/2f9b60de0da46ba65383698fe93d35db24973d60348f457d6d5b7343
	new file:   .cache/pip/http/a/1/9/5/3/a19537d3cf37c122db841d6fe4cd322bc10d1a558bb00d146b85cb9a
	new file:   .cache/pip/selfcheck/ab2bb442149194bcbab5700d8f932112632ba9320db09910f4a4422b
	new file:   .conda/environments.txt
	new file:   .ipynb_checkpoints/numpy-array-operations-checkpoint.ipynb
	new file:   .ipython/profile_default/history.sqlite
	new file:   .ipython/profile_default/startup/README
	new file:   .jovian/credentials.json
	modified:   .jovianrc
	new file:   .jupyter/jupyter_notebook_config.py
	new file:   .jupyter/nbconfig/common.json
	new file:   .local/share/jupyter/nbsignatures.db
	new file:   .local/share/jupyter/notebook_secret
	new file

In [52]:
!git add numpy-array-operation.ipynb

fatal: pathspec 'numpy-array-operation' did not match any files
